language: java

sudo: required

dist: trusty

services:
  - docker

cache:
  directories:
  - "$HOME/.gradle"

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      env:
        - DOCKER_USER=xenitpublisher
        - secure: "iFUkQ3TSEsmt+GaagRTkt+HrmZgPN3yhuEBRzdb93V/gJQjJHLeaEFUtlyjBfLbRX4D4WflS97sHKPgN+T05+YAv/kmqiRIzb/ogRz24y2rcO+57gYfcbcUv4rm6OTxTRGS/404hCAlt9IZvTcxSogeNqAuQw+bMg1WdcONaKr5XnbWXFiNakIntNReb7/6rWcH7jo9GwXygkY8HJGgbpEDqbb8/hliNjaF2lTo6+EmDeQ5MmaJCLGyLDxpSaKOGKxbsFLagXFRZlV4W8m/jfeIalF8G5nqbXaHyYdPW7mr45wsZQ0qx3NFesu41iOY2vHAm3z6FuyE7NvXam1lpaz1tumpFD+mxJMN5CiGCK4OnXpXmHm5+2H+5dbnCXcGaTI4Pmt/rsUs0J5TPNvLTtKPEZm5RZOqNbgZVQrXHakSvrX5adHvE4PkCBxXJ6QSTVMSuyflFqko3rArNXGjRpquj53NMbV6qCK6iPPEdt6JwYE+y5PsiCkUxSs2YJkGjeWqFukZnMrOlok/3uSleAX4MVTQNNumkAM2VHamlqBdGcgr97wYUr+ITSWJGh0DNXMLIsx3CUx3OF7OIyy1y1dWDILsfLj1GUKmK98iphJ1cY87sQ1J22IV8++LB1fIrAn64bSZa0i/7lqPmf7Xae3NdeoPziunbwlSq0FOTn10="
      before_install:
        - chmod +x ./gradlew
        - sudo apt-get install libreoffice
      script:
              #        - ./gradlew build -x test -x integrationTest
        - if [[ $TRAVIS_BRANCH = "master" ]] ; then ./gradlew pushDockerImage ; fi



