server:
  port: 8080
  tomcat:
    access-log:
      enabled: true
      directory: "/tmp/"
      prefix: stdout
      pattern: "%h %l %u %t \"%r\" %s %b %D"

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  application:
    name: JODConverter Sample Rest Api

jodconverter:
  local:
    enabled: true
    port-numbers: 2002,2003
    format-options:
      html:
        store:
          TEXT:
            FilterOptions: EmbedImages

      xhtml:
        store:
          TEXT:
            FilterOptions: EmbedImages

logging:
  level:
    org.jodconverter: debug
